"use client";
import React, { useState } from "react";

type QA = {
  content: string;
  isAI: boolean;
  isTrue: boolean;
  explanation: string;
};

const QUESTIONS: QA[] = [
  {
    content: "The Great Wall of China is visible from space.",
    isAI: true,
    isTrue: false,
    explanation:
      "This is a common myth. The Great Wall is not visible from space with the naked eye. This answer was generated by AI and is confidently wrong (hallucination).",
  },
  {
    content:
      "Honey never spoils. Archaeologists have found edible honey in ancient Egyptian tombs.",
    isAI: false,
    isTrue: true,
    explanation:
      "This is true! Honey's chemical makeup makes it inhospitable to bacteria and microorganisms. This answer was written by a human.",
  },
  {
    content: "Bananas grow on trees.",
    isAI: true,
    isTrue: false,
    explanation:
      "Bananas actually grow on large herbaceous plants, not trees. This is a confidently wrong AI answer (hallucination).",
  },
  {
    content: "The capital of Australia is Sydney.",
    isAI: false,
    isTrue: false,
    explanation:
      "This is false. The capital of Australia is Canberra. This answer was written by a human.",
  },
  {
    content: "Sharks are mammals.",
    isAI: true,
    isTrue: false,
    explanation:
      "Sharks are fish, not mammals. This answer was generated by AI and is incorrect.",
  },
  {
    content: "The Eiffel Tower is located in Paris.",
    isAI: false,
    isTrue: true,
    explanation:
      "This is true! The Eiffel Tower is a famous landmark in Paris, France. This answer was written by a human.",
  },
  {
    content: "Lightning never strikes the same place twice.",
    isAI: true,
    isTrue: false,
    explanation:
      "This is a myth. Lightning can and does strike the same place multiple times. This answer was generated by AI and is confidently wrong.",
  },
  {
    content: "Octopuses have three hearts.",
    isAI: false,
    isTrue: true,
    explanation:
      "This is true! Octopuses have three hearts. This answer was written by a human.",
  },
];

function getRandomIndex(max: number, exclude: number) {
  let idx = Math.floor(Math.random() * max);
  while (idx === exclude) {
    idx = Math.floor(Math.random() * max);
  }
  return idx;
}

export default function AITruthTest() {
  const [questionIdx, setQuestionIdx] = useState(0);
  const [guessAI, setGuessAI] = useState<null | boolean>(null);
  const [guessTrue, setGuessTrue] = useState<null | boolean>(null);
  const [showResult, setShowResult] = useState(false);

  const question = QUESTIONS[questionIdx];

  const handleGuess = (ai: boolean | null, truth: boolean | null) => {
    setGuessAI(ai);
    setGuessTrue(truth);
    setShowResult(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (guessAI !== null && guessTrue !== null) setShowResult(true);
  };

  const handleNext = () => {
    setShowResult(false);
    setGuessAI(null);
    setGuessTrue(null);
    setQuestionIdx((prev) => getRandomIndex(QUESTIONS.length, prev));
  };

  return (
    <div
      style={{
        background: "#fff",
        borderRadius: 16,
        boxShadow: "0 2px 16px 0 rgba(217,118,86,0.08)",
        padding: 32,
        maxWidth: 540,
        margin: "0 auto",
        marginTop: 32,
      }}
    >
      <h2 style={{ color: "#d97656", marginBottom: 16 }}>
        🤖 AI Truth Test: Real or Robot?
      </h2>
      <div style={{ fontSize: 18, marginBottom: 18 }}>
        <b>Read the statement below. Can you guess:</b>
        <ul style={{ margin: "10px 0 0 18px", color: "#444", fontSize: 16 }}>
          <li>Was it written by AI or a human?</li>
          <li>Is it factually correct?</li>
        </ul>
      </div>
      <div
        style={{
          background: "#f7fafd",
          borderRadius: 12,
          padding: 18,
          fontSize: 20,
          color: "#222",
          marginBottom: 20,
          border: "1.5px solid #e3edfa",
          textAlign: "center",
        }}
      >
        <b>{question.content}</b>
      </div>
      <form onSubmit={handleSubmit}>
        <div
          style={{
            marginBottom: 18,
            display: "flex",
            gap: 24,
            justifyContent: "center",
          }}
        >
          <div>
            <div style={{ fontWeight: 600, marginBottom: 6 }}>
              Who wrote it?
            </div>
            <button
              type="button"
              onClick={() => handleGuess(true, guessTrue)}
              style={{
                background: guessAI === true ? "#eafbe7" : "#fff7f2",
                color: guessAI === true ? "#2e7d32" : "#d97656",
                border:
                  guessAI === true
                    ? "2px solid #6ee7b7"
                    : "1.5px solid #ffd7b3",
                borderRadius: 18,
                padding: "8px 18px",
                marginRight: 8,
                fontWeight: 600,
                fontSize: 16,
                cursor: "pointer",
                transition: "all 0.15s",
              }}
            >
              AI
            </button>
            <button
              type="button"
              onClick={() => handleGuess(false, guessTrue)}
              style={{
                background: guessAI === false ? "#eafbe7" : "#fff7f2",
                color: guessAI === false ? "#2e7d32" : "#d97656",
                border:
                  guessAI === false
                    ? "2px solid #6ee7b7"
                    : "1.5px solid #ffd7b3",
                borderRadius: 18,
                padding: "8px 18px",
                fontWeight: 600,
                fontSize: 16,
                cursor: "pointer",
                transition: "all 0.15s",
              }}
            >
              Human
            </button>
          </div>
          <div>
            <div style={{ fontWeight: 600, marginBottom: 6 }}>Is it true?</div>
            <button
              type="button"
              onClick={() => handleGuess(guessAI, true)}
              style={{
                background: guessTrue === true ? "#eafbe7" : "#fff7f2",
                color: guessTrue === true ? "#2e7d32" : "#d97656",
                border:
                  guessTrue === true
                    ? "2px solid #6ee7b7"
                    : "1.5px solid #ffd7b3",
                borderRadius: 18,
                padding: "8px 18px",
                marginRight: 8,
                fontWeight: 600,
                fontSize: 16,
                cursor: "pointer",
                transition: "all 0.15s",
              }}
            >
              True
            </button>
            <button
              type="button"
              onClick={() => handleGuess(guessAI, false)}
              style={{
                background: guessTrue === false ? "#eafbe7" : "#fff7f2",
                color: guessTrue === false ? "#2e7d32" : "#d97656",
                border:
                  guessTrue === false
                    ? "2px solid #6ee7b7"
                    : "1.5px solid #ffd7b3",
                borderRadius: 18,
                padding: "8px 18px",
                fontWeight: 600,
                fontSize: 16,
                cursor: "pointer",
                transition: "all 0.15s",
              }}
            >
              False
            </button>
          </div>
        </div>
        <button
          type="submit"
          style={{
            background: "#d97656",
            color: "#fff",
            border: "none",
            borderRadius: 20,
            padding: "10px 32px",
            fontSize: 18,
            fontWeight: 700,
            cursor: "pointer",
            marginBottom: 8,
            boxShadow: "0 2px 8px 0 rgba(217,118,86,0.08)",
            marginTop: 10,
            display: "block",
            marginLeft: "auto",
            marginRight: "auto",
          }}
          disabled={guessAI === null || guessTrue === null}
        >
          Reveal Answer
        </button>
      </form>
      {showResult && (
        <div
          style={{
            marginTop: 22,
            background: "#fff7f2",
            borderRadius: 12,
            padding: 18,
            fontSize: 17,
            color: "#222",
            minHeight: 48,
            border: "1.5px solid #ffd7b3",
          }}
        >
          <div>
            <b>AI or Human?</b>{" "}
            <span style={{ color: question.isAI ? "#d97656" : "#2e7d32" }}>
              {question.isAI ? "AI" : "Human"}
            </span>
            {guessAI === question.isAI ? (
              <span style={{ color: "#2e7d32", marginLeft: 8 }}>✔️</span>
            ) : (
              <span style={{ color: "#d97656", marginLeft: 8 }}>✖️</span>
            )}
          </div>
          <div style={{ marginTop: 10 }}>
            <b>True or False?</b>{" "}
            <span style={{ color: question.isTrue ? "#2e7d32" : "#d97656" }}>
              {question.isTrue ? "True" : "False"}
            </span>
            {guessTrue === question.isTrue ? (
              <span style={{ color: "#2e7d32", marginLeft: 8 }}>✔️</span>
            ) : (
              <span style={{ color: "#d97656", marginLeft: 8 }}>✖️</span>
            )}
          </div>
          <div style={{ marginTop: 16, fontSize: 15, color: "#888" }}>
            <b>Explanation:</b> {question.explanation}
          </div>
          <div style={{ marginTop: 18, color: "#888", fontSize: 15 }}>
            <b>Discuss:</b> Did the AI <b>lie</b>, or was it just
            wrong/confused? <br />
            <span style={{ color: "#d97656" }}>
              Hallucinations ≠ lying, but AIs can mislead!
            </span>
          </div>
          <button
            onClick={handleNext}
            style={{
              marginTop: 18,
              background: "#fff",
              color: "#d97656",
              border: "1.5px solid #ffd7b3",
              borderRadius: 18,
              padding: "8px 22px",
              fontWeight: 600,
              fontSize: 16,
              cursor: "pointer",
              transition: "all 0.15s",
              display: "block",
              marginLeft: "auto",
              marginRight: "auto",
            }}
          >
            Try Another
          </button>
        </div>
      )}
      <div style={{ marginTop: 28, color: "#888", fontSize: 15 }}>
        <b>Why?</b> Sometimes AI makes things up ("hallucinates") but it's not
        the same as lying. Always check facts!
      </div>
    </div>
  );
}
